package Model;
// Generated Nov 6, 2019 7:38:26 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String userCustomer;
     private String passwordCustomer;
     private String nameCustomer;
     private String email;
     private String phoneNumber;
     private Boolean roleCustomer;
     private String addressCustomer;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public Customer() {
    }

	
    public Customer(String userCustomer, String passwordCustomer, String nameCustomer, String phoneNumber) {
        this.userCustomer = userCustomer;
        this.passwordCustomer = passwordCustomer;
        this.nameCustomer = nameCustomer;
        this.phoneNumber = phoneNumber;
    }
    public Customer(String userCustomer, String passwordCustomer, String nameCustomer, String email, String phoneNumber, Boolean roleCustomer, String addressCustomer) {
       this.userCustomer = userCustomer;
       this.passwordCustomer = passwordCustomer;
       this.nameCustomer = nameCustomer;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.roleCustomer = roleCustomer;
       this.addressCustomer = addressCustomer;
    }
   
    public String getUserCustomer() {
        return this.userCustomer;
    }
    
    public void setUserCustomer(String userCustomer) {
        this.userCustomer = userCustomer;
    }

    public String getAddressCustomer() {
        return addressCustomer;
    }

    public void setAddressCustomer(String addressCustomer) {
        this.addressCustomer = addressCustomer;
    }
    public String getPasswordCustomer() {
        return this.passwordCustomer;
    }
    
    public void setPasswordCustomer(String passwordCustomer) {
        this.passwordCustomer = passwordCustomer;
    }
    public String getNameCustomer() {
        return this.nameCustomer;
    }
    
    public void setNameCustomer(String nameCustomer) {
        this.nameCustomer = nameCustomer;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Boolean getRoleCustomer() {
        return this.roleCustomer;
    }
    
    public void setRoleCustomer(Boolean roleCustomer) {
        this.roleCustomer = roleCustomer;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


