package Model;
// Generated Nov 6, 2019 7:38:26 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.sql.Time;
import java.sql.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private int idInvoice;
     private Customer customer;
     private Product product;
     private int amount;
     private Date dateOrder;
     private int total;

    public Invoice() {
    }

	
    public Invoice(int idInvoice, Customer customer, Product product, int amount,Date dateOrder, int total) {
        this.idInvoice = idInvoice;
        this.customer = customer;
        this.product = product;
        this.amount = amount;
        this.total = total;
           this.dateOrder = dateOrder;
    }

    
   
    public int getIdInvoice() {
        return this.idInvoice;
    }
    
    public void setIdInvoice(int idInvoice) {
        this.idInvoice = idInvoice;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public Date getDateOrder() {
        return this.dateOrder;
    }
    
    public void setDateOrder(Date dateOrder) {
        this.dateOrder = dateOrder;
    }
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }




}


