package Model;
// Generated Nov 6, 2019 7:38:26 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Producer generated by hbm2java
 */
public class Producer  implements java.io.Serializable {


     private String idProducer;
     private String nameProducer;
     private Set<Product> products = new HashSet<Product>(0);

    public Producer() {
    }

	
    public Producer(String idProducer, String nameProducer) {
        this.idProducer = idProducer;
        this.nameProducer = nameProducer;
    }
    public Producer(String idProducer, String nameProducer, Set<Product> products) {
       this.idProducer = idProducer;
       this.nameProducer = nameProducer;
       this.products = products;
    }
   
    public String getIdProducer() {
        return this.idProducer;
    }
    
    public void setIdProducer(String idProducer) {
        this.idProducer = idProducer;
    }
    public String getNameProducer() {
        return this.nameProducer;
    }
    
    public void setNameProducer(String nameProducer) {
        this.nameProducer = nameProducer;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }


public String toString(){
    return nameProducer;
}

}


