package Model;
// Generated Nov 6, 2019 7:38:26 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * TypeProduct generated by hbm2java
 */
public class TypeProduct  implements java.io.Serializable {


     private String idProductType;
     private String nameProductType;
     private Set<Product> products = new HashSet<Product>(0);

    public TypeProduct() {
    }

	
    public TypeProduct(String idProductType, String nameProductType) {
        this.idProductType = idProductType;
        this.nameProductType = nameProductType;
    }
    public TypeProduct(String idProductType, String nameProductType, Set<Product> products) {
       this.idProductType = idProductType;
       this.nameProductType = nameProductType;
       this.products = products;
    }
   
    public String getIdProductType() {
        return this.idProductType;
    }
    
    public void setIdProductType(String idProductType) {
        this.idProductType = idProductType;
    }
    public String getNameProductType() {
        return this.nameProductType;
    }
    
    public void setNameProductType(String nameProductType) {
        this.nameProductType = nameProductType;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }


public String toString(){
    return nameProductType;
}


}


